global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'project1'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
